---
title: "Pre-Processing"
output: html_document
date: "2025-08-04"
---

#Read data
```{r}
data <- read.csv("https://raw.githubusercontent.com/arinbasu/data309/refs/heads/main/diabetes_prediction_data.csv")

```

#View data
```{r}
View(data)
```

#Clean the data
```{r}
data1 <- data %>%
  rename(
    Gender = gender,
    Age = age,
    Hypertension = hypertension,
    "Heart Disease" = heart_disease,
    "Smoking History" = smoking_history,
    "BMI (kg/m^2)" = bmi,
    "HbA1c Level (mmol)" = HbA1c_level,
    "Blood Glucose Level (mg/dl)" = blood_glucose_level,
    Diabetes = diabetes)

View(data1)
glimpse(data1)
```

#Check for missing and duplicated data
```{r}
duplicated_data <- data1 %>%
  filter(duplicated(.))
View(duplicated_data)

duplicate_count <- nrow(duplicated_data)
print(paste("Total Duplicated Data:", duplicate_count))

anyNA(data1$Gender)
anyNA(data1$`Heart Disease`)
anyNA(data1$Diabetes)
```

#Variable selection
```{r}
glimpse(data1 %>%
      select("Gender", "Heart Disease", "Diabetes"))

data2 <- data1 %>%
  mutate(
    Gender = as.factor(Gender),
    `Heart Disease` = factor(`Heart Disease`, levels = c(0, 1), labels = c("No", "Yes")),
    Diabetes = factor(Diabetes, levels = c(0, 1), labels = c("No", "Yes")))

data2 %>%
  summarise(
    Gender_Count = list(table(Gender)),
    Heart_Disease_Count = list(table(`Heart Disease`)),
    Diabetes_Count = list(table(Diabetes))
  )
```

#Summary
```{r}
#gender
"Frequency count for Gender" 
summary(data2$Gender)

#heart disease
"Frequency count for Heart Disease"
summary(data2$`Heart Disease`)

#diabetes
"Frequency count for diabetes"
summary(data2$Diabetes)
```

#Plots
```{r}
data2 %>%
  ggplot(aes(x = `Heart Disease`)) +
  geom_bar() +
  labs(title = "Heart Disease Distribution", x = "Heart Disease", y = "Count") +
  theme_minimal()

data2 %>%
  ggplot(aes(x = Gender)) +
  geom_bar() +
  labs(title = "Gender Distribution", x = "Gender", y = "Count") +
  theme_minimal()

data2 %>%
  ggplot(aes(x = Diabetes)) +
  geom_bar() +
  labs(title = "Diabetes Distribution", x = "Diabetes", y = "Count") +
  theme_minimal()
```
